# Generated by Django 4.2.7 on 2025-11-02 17:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20, verbose_name='Gender')),
                ('height', models.CharField(blank=True, max_length=50, verbose_name='Height')),
                ('weight', models.CharField(blank=True, max_length=50, verbose_name='Weight')),
                ('hair_color', models.CharField(blank=True, max_length=50, verbose_name='Hair Color')),
                ('eye_color', models.CharField(blank=True, max_length=50, verbose_name='Eye Color')),
                ('distinguishing_features', models.TextField(blank=True, verbose_name='Distinguishing Features')),
                ('last_seen_date', models.DateField(verbose_name='Last Seen Date')),
                ('last_seen_location', models.CharField(max_length=300, verbose_name='Last Seen Location')),
                ('circumstances', models.TextField(verbose_name='Circumstances')),
                ('contact_name', models.CharField(max_length=200, verbose_name='Contact Person Name')),
                ('contact_phone', models.CharField(max_length=50, verbose_name='Contact Phone Number')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('police_case_number', models.CharField(blank=True, max_length=100, verbose_name='Police Case Number')),
                ('police_department', models.CharField(blank=True, max_length=200, verbose_name='Police Department')),
                ('photo', models.ImageField(upload_to='missing_persons/photos/%Y/%m/', verbose_name="Person's Photo")),
                ('digital_flyer', models.FileField(upload_to='missing_persons/flyers/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Digital Flyer')),
                ('ar_marker_image', models.ImageField(blank=True, null=True, upload_to='missing_persons/markers/%Y/%m/', verbose_name='AR Marker Image')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Upload Date')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_persons', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Missing Person',
                'verbose_name_plural': 'Missing Persons',
                'ordering': ['-upload_date'],
            },
        ),
    ]
