# Generated by Django 4.2.7 on 2025-11-02 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='digital_flyer',
            field=models.FileField(blank=True, null=True, upload_to='missing_persons/flyers/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Digital Flyer'),
        ),
    ]
